### ISSUE TITLE
[New Core]: psomashekar - Snow Bros. 2

### ISSUE THREAD

**Issue by joshcampbell191** [neil-morrison44/analogue-pocket#21]
### Core Author username

psomashekar

### Core .yml snippet

```yml
display_name: Snow Bros. 2
repository: pram0d-pocket-dist-public
path: releases/pram0d.snowbros2_20221019.zip
```
